config/routes.rb
Rails.application.routes.draw do

  root 'jobs#index'
  get     '/login',    to: 'sessions#new'
  post    '/login',    to: 'sessions#create'
  delete  '/logout',   to: 'sessions#destroy'
  get     '/signup',   to: 'employers#new'
  resources :jobs
  resources :proposals, only: :create
  resources :employers, only: [:show, :create]
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/employer.rb
class Employer < ApplicationRecord
	has_many :jobs
	
	before_save { self.email = email.downcase }
	
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
	
	validates :name,     presence: true, length: { minimum: 5 }
	validates :email,    presence: true, length: { maximum: 255 }, uniqueness: { case_sensitive: false },
																															   format:		 { with: VALID_EMAIL_REGEX }
	validates :password, presence: true, length: { minimum: 6 }
	has_secure_password
end

app/models/job.rb
class Job < ApplicationRecord
  belongs_to :employer
  has_many :proposals
  
  default_scope -> { order(created_at: :desc) }
  
  validates :title, :description, :employer, presence: true
end

app/models/proposal.rb
class Proposal < ApplicationRecord
  belongs_to :job, dependent: :destroy
  
  default_scope -> { order(created_at: :desc) }
  
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  
  validates :name, :content, :job, presence: true
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  include SessionsHelper
  
  private
    
    def logged_in_employer
      unless logged_in?
        flash[:danger] = "Please, Log in."
        redirect_to login_url
      end
    end
    
end

app/controllers/employers_controller.rb
class EmployersController < ApplicationController
  before_action :logged_in_employer, only: :show
  
  def show
    @employer = Employer.find(params[:id])
  end

  def new
    @employer = Employer.new
  end
  
  def create
    @employer = Employer.new(employer_params)
    if @employer.save
      log_in @employer
      flash[:success] = 'Create account successfully'
      redirect_to @employer
    else
      render 'new'
    end
  end
  
  private
    
    def employer_params
      params.require(:employer).permit(:name, :email, :password, :password_confirmation)
    end
  
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :logged_in_employer, only: [:new, :create]
  
  def index
    @jobs = Job.all
  end

  def show
    @job = Job.find(params[:id])
    @current_job = @job
    @proposal = Proposal.new
  end

  def new
    @job = current_employer.jobs.build
  end
  
  def create
    @job = current_employer.jobs.build(job_params)
    if @job.save
      flash[:success] = 'Job created successfully'
      redirect_to @job
    else
      render 'new'
    end
  end
  
  private
  
    def job_params
      params.require(:job).permit(:title, :description)
    end
  
end

app/controllers/proposals_controller.rb
class ProposalsController < ApplicationController
	
	def create
		@job = Job.find_by(id: params[:current_job])
		@proposal = @job.proposals.build(proposal_params)
		if @proposal.save
			flash[:success] = 'proposal sent.'
			redirect_to jobs_path
		else
			render 'new'
		end
	end
	
	private
		
		def proposal_params
			params.require(:proposal).permit(:name, :email, :content)
		end
		
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
  end
  
  def create
    employer = Employer.find_by(email: params[:session][:email].downcase)
    if employer && employer.authenticate(params[:session][:password])
      log_in employer
      redirect_to employer
    else
      flash[:danger].now = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employers_helper.rb
module EmployersHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/proposals_helper.rb
module ProposalsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	
	def log_in(employer)
		session[:employer_id] = employer.id
	end
	
	def current_employer
		@current_employer ||= Employer.find_by(id: session[:employer_id])
	end
	
	def current_employer?(employer)
		current_employer == employer
	end
	
	def logged_in?
		!current_employer.nil?
	end
	
	def log_out
		session.delete(:employer_id)
		current_employer = nil
	end
	
end

app/views/employers/new.html.erb
<h1>Sign up as an employer</h1>

<div>
	<%= form_for(@employer) do |f| %>
		
		<p>
			<%= f.label :name %>
			<%= f.text_field :name %>
		</p>
		
		<p>
			<%= f.label :email %>
			<%= f.text_field :email %>
		</p>
		
		<p>
			<%= f.label :password %>
			<%= f.password_field :password %>
		</p>
		
		<p>
			<%= f.label :password_confirmation %>
			<%= f.password_field :password_confirmation %>
		</p>
		
		<p>
			<%= f.submit 'Sign up' %>
		</p>
		
	<% end %>
</div>

app/views/employers/show.html.erb
<h2><%= @employer.name.capitalize %></h2>
<h5><%= @employer.jobs.count %> jobs posted.</h5>

<% if current_employer?(@employer) %>
	<p><%= link_to 'Post a job', new_job_path %></p>
<% end %>

<h2>Jobs posted:</h2>
<%= render @employer.jobs %>

app/views/jobs/_job.html.erb
<p>
	<h4><%= link_to "#{job.title}", job_path %></h4>
	<p><%= job.description %></p>
	<span><small>created at: <%= job.created_at.strftime("%Y-%m-%d %H:%M:%S") %></small></span>
</p>

app/views/jobs/index.html.erb
<h1>Available Jobs:</h1>

<% @jobs.each do |job| %>
	<p>
		<span><strong><%= link_to "#{job.title}", job_path(job) %></strong></span>
		<br>
		<span><%= job.description.truncate(27) %></span>
		<br>
		<span><small>created at: <%= job.created_at.strftime("%Y-%m-%d %H:%M:%S") %></small></span>
	</p>
<% end %>

<% unless logged_in? %>
	<div>-----------------------------------------------</div>
	<div>If you're an employer click <span><%= link_to 'here', login_path %></span></div>
<% end %>

app/views/jobs/new.html.erb
<h1>Post a new job:</h1>

<%= form_for(@job) do |f| %>

	<p>
		<%= f.label :title %>
		<%= f.text_field :title %>
	</p>
	
	<p>
		<%= f.label :description %>
		<%= f.text_area :description %>
	</p>
	
	<%= f.submit 'Post' %>
	
<% end %>

app/views/jobs/show.html.erb
<%= render @job %>

<% if current_employer?(@job.employer) %>
	Number of proposals: <%= @job.proposals.count %>
	<p>------------------------------</p>
	<h3>Proposals:</h3>
	<%= render @job.proposals %>
<% end %>

<p>
	<% unless logged_in? %>
		<p>---------------------------</p>
		<%= render 'proposals/new' %>
	<% end %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JobForum</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p>
      <%= link_to 'Home', root_url %>
      <% if logged_in? %> <%= link_to 'Profile', employer_path(current_employer) %> <% end %>
      <% if logged_in? %> <%= link_to 'Log out', logout_path, method: :delete %> <% end %>
    </p>
    <%= yield %>
  </body>
</html>

app/views/proposals/_new.html.erb
<h3>Send a proposal:</h3>

<%= form_for(@proposal) do |f| %>

	<%= hidden_field_tag :current_job, @current_job.id %>
	
	<p>
		<%= f.label :name %>
		<%= f.text_field :name %>
	</p>
	
	<p>
		<%= f.label :email %>
		<%= f.text_field :email %>
	</p>
	
	<p>
		<%= f.label :content %>
		<%= f.text_area :content %>
	</p>
	
	<%= f.submit 'Send' %>

<% end %>

app/views/proposals/_proposal.html.erb
<p>
	<%= proposal.name %>
	<br>
	<%= proposal.email %>
	<p>
	<%= proposal.content %>
	</p>
	<span><small><%= proposal.created_at.strftime("%Y-%m-%d %H:%M:%S") %></span></small>
</p>